FROM python:3.12-slim

WORKDIR /app

COPY src/demo/requirements-demo.txt .

RUN pip install --no-cache-dir -r requirements-demo.txt

COPY src/demo ./src/demo

EXPOSE 8501

CMD ["streamlit", "run", "src/demo/app.py", "--server.address=0.0.0.0", "--server.port=8501"]